export const labels: Record<string, string> = {
  construct: '造竜種',
  'flying-wyvern': '飛竜種',
  'brute-wyvern': '獣竜種',
  'fanged-wyvern': '牙竜種',
  'leviathan': '海竜種',
  'temnoceran': '鋏角種',
  'carapaceon': '甲殻種',
  'fanged-beast': '牙獣種',
  'bird-wyvern': '鳥竜種',
  'elder-dragon': '古龍種',
  low: '下位',
  high: '上位',
  master: 'マスター',
  'target-reward': 'ターゲット報酬',
  carve: '剥ぎ取り',
  'carve-severed': '切断部位の剥ぎ取り',
  'carve-rotten': '変質部位の剥ぎ取り',
  'carve-rotten-severed': '変質した切断部位の剥ぎ取り',
  'wound-destroyed': '傷口破壊',
  'broken-part': '部位破壊',
  fire: '火',
  water: '水',
  thunder: '雷',
  ice: '氷',
  dragon: '龍',
  poison: '毒',
  paralysis: '麻痺',
  sleep: '睡眠',
  blastblight: '爆破やられ',
  stun: '気絶',
  flash: '閃光',
  noise: '音',
  exhaust: '減気',
  slash: '斬',
  blunt: '打',
  pierce: '弾',
  consumable: '消費アイテム',
  material: '素材',
  ammo: '弾・ビン',
  account: '精算アイテム',
  special: '重要アイテム',
};

export function label(value?: string) {
  if (!value) return '不明';
  return labels[value] ?? value;
}
